"""add user.resume

Revision ID: 15dc34639677
Revises: ecccdbc6a5e9
Create Date: 2018-11-10 15:19:02.351579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15dc34639677'
down_revision = 'ecccdbc6a5e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('resume_url', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'resume_url')
    # ### end Alembic commands ###
